name: ume_core
description: UME is an in-app debug kits platform for Flutter apps.
version: 2.0.1
homepage: https://github.com/ume-community/ume_core
topics: [debug, in-app-debug, diagnostics, console, plugin, ume]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.3.3

  vm_service: ^15.0.0

  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65
  # lints: ^5.1.0

flutter:
  uses-material-design: true
